[package]
name = "rust-strengths-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7"
clap = { version = "4.0", features = ["derive"] }
