[package]
name = "matrix-multiplier"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "matrix-multiplier"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
rayon = "1.8"
rand = "0.8"
